public with sharing class OutboundTransactionHelper {
    public static final String STATUS_READY_TO_SEND = 'Ready to send';
    public static final String STATUS_READY_TO_SIGN = 'Ready to Sign';
    public static final String STATUS_SENT = 'Sent';
    public static final String STATUS_REJECTED = 'Rejected';
    public static final String APPROVAL_STATUS_APPROVED = 'Approved';
    public static final String APPROVAL_STATUS_NOT_APPROVED = 'Not Approved';
    public static final Integer MIN_TRANSACTION_HASH_LENGTH = 64;
} 